Repository CheatSOL/CheatSOL-FE, pull requests merged in 2024-06, with the labels that each got.

#1 ✅test: Landing.jsx - 테스트 코드 작성
  src/pages/landing/Landing.jsx
Labels: :truck: rename

#2 TEST: merge test
  src/pages/landing/Landing.jsx
Labels: :white_check_mark: test

#18 FEAT : 헤더 컴포넌트 생성
  .gitignore
  package-lock.json
  package.json
  src/App.css
  src/components/common/header/Header.jsx
  src/components/common/header/Header.style.js
  src/components/common/logo/Logo.style.js
  src/components/common/sidebar/Sidebar.jsx
  src/index.css
Labels: 🎉 init, ✨ Feature, :gem: epic

#20 버블 컴포넌트 구현 완료
  src/components/common/bubble/KeywordBubble.jsx
  src/components/common/bubble/KeywordBubble.style.js
Labels: :page_facing_up: task

#21 ✨feat: 컨텐츠 아이템(주식회사) 컴포넌트 구현완료
  src/components/common/contents-item/Contents.jsx
  src/components/common/contents-item/Contents.style.js
  src/pages/stock/Stock.jsx
Labels: :page_facing_up: task

#22 FEAT: 컨텐츠 맵 컴포넌트 - 구글 뉴스 구현 완료
  src/components/common/news/google-news/Google.news.jsx
  src/components/common/news/google-news/Google.style.js
  src/pages/main/Main.jsx
Labels: :page_facing_up: task

#23 ✨feat: 컨텐츠 맵 컴포넌트 - 유튜브 데이터 구현 완료
  public/assets/images/down-icon.png
  public/assets/images/up-icon.png
  src/components/common/contents-item/Contents.jsx
  src/components/common/news/youtube-data/Youtube.data.jsx
  src/components/common/news/youtube-data/Youtube.data.style.js
  src/pages/social/Social.jsx
  src/pages/stock/Stock.jsx
  vite.config.js
Labels: :page_facing_up: task

#24 FEAT: 컨텐츠 전체 매핑 컴포넌트 생성 구현 완료 - 네이버 , 연관 키워드
  src/components/common/news/keyword-blog/Keyword.blog.jsx
  src/components/common/news/keyword-blog/Keyword.style.js
  src/components/common/news/naver-news/Naver.news.jsx
  src/components/common/news/naver-news/Naver.style.js
Labels: :page_facing_up: task

#32 Feat: 디폴트 그래프 보여주기 구현완료
  public/assets/images/google.png
  public/assets/images/instagram-logo.png
  public/assets/images/instagram.png
  public/assets/images/logo.png
  public/assets/images/naver.png
  public/assets/images/youtube.png
  src/components/common/chart-select-bar/country/Country.style.js
  src/components/common/chart-select-bar/period/Period.style.js
  src/components/common/header/Header.style.js
  src/components/common/logo/Logo.jsx
  src/components/common/news/google-news/Google.news.jsx
  src/components/common/news/google-news/Google.style.js
  src/components/common/news/instagram-data/instagram.data.style.js
  src/components/common/news/naver-news/Naver.news.jsx
  src/components/common/news/naver-news/Naver.style.js
  src/components/common/news/youtube-data/Youtube.data.style.js
  src/components/common/scroll-top-button/Scroll.top.button.jsx
  src/components/common/sidebar/Sidebar.jsx
  src/components/common/sidebar/Sidebar.style.js
  src/pages/social/Google.item.jsx
  src/pages/social/Google.style.js
  src/pages/social/Instagram.item.jsx
  src/pages/social/Instagram.style.js
  src/pages/social/NaverItem.jsx
  src/pages/social/NaverItem.style.js
  src/pages/social/Social.jsx
  src/pages/social/Social.style.js
  src/pages/social/Youtube.item.jsx
  src/pages/social/Youtube.style.js
Labels: :page_facing_up: task

#38 Feat: 랜딩페이지 디자인 구현 완료
  public/assets/images/landing.png
  src/pages/landing/Bubble.jsx
  src/pages/landing/Bubble.style.js
  src/pages/landing/Landing.Search.jsx
  src/pages/landing/Landing.Search.style.js
  src/pages/landing/Landing.jsx
  src/pages/landing/Landing.style.js
Labels: :page_facing_up: task

#33 ✨feat: 연관주 상세페이지 통합탭 표 부분 구현완료
  src/App.jsx
  src/pages/stock/detail/maintab/Maintab.jsx
  src/pages/stock/detail/maintab/Maintab.style.js
  src/pages/stock/detail/maintab/currentPrice.js
Labels: ✨ Feature

#37 ✨feat: 연관주 상세페이지 시세탭 표 부분 구현완료
  index.html
  package.json
  src/App.jsx
  src/pages/stock/detail/pricetab/Pricetab.jsx
  src/pages/stock/detail/pricetab/Pricetab.style.js
  src/pages/stock/detail/pricetab/dailyPrice.js
Labels: ✨ Feature

#43 ✨Feat: 한투 api 일별 현재가, 현재가 로직 백엔드로 이동
  package-lock.json
  package.json
  src/pages/stock/detail/maintab/Maintab.jsx
  src/pages/stock/detail/maintab/currentPrice.js
  src/pages/stock/detail/pricetab/Pricetab.jsx
  src/pages/stock/detail/pricetab/dailyPrice.js
  vite.config.js
Labels: ✨ Feature

#46 Feat/ TASK : 2. 연관 주식시세 및 검색어트래픽 차트 구현 완료
  package-lock.json
  package.json
  src/App.jsx
  src/components/common/scroll-top-button/Scroll.top.button.jsx
  src/components/common/sidebar/Sidebar.jsx
  src/components/common/sidebar/Sidebar.style.js
  src/pages/stock/Stock.chart.jsx
  src/pages/stock/Stock.jsx
  src/pages/stock/Stock.style.js
Labels: :page_facing_up: task

#48 ✨feat: 연관키워드 버블 구현완료
  src/components/common/bubble-relatedkeyword/RelatedKeyword.jsx
  src/components/common/bubble-relatedkeyword/RelatedKeyword.style.js
  src/components/common/bubble/KeywordBubble.jsx
  src/components/common/bubble/KeywordBubble.style.js
  src/pages/keyword/Keyword.jsx
Labels: ✨ Feature, :book: story, :page_facing_up: task

#50 Feat/ Redux toolkit를 사용해서 현재 검색어 저장 완료
  package-lock.json
  src/App.jsx
  src/components/common/search/Search.jsx
  src/components/common/search/Search.style.js
  src/pages/landing/Landing.Search.jsx
  src/pages/stock/Stock.jsx
  src/store/reducers/search.js
  src/store/store.js
Labels: :page_facing_up: task

#49 ✨Feat: 기업 상세 페이지- 뉴스탭 구현 완료
  src/App.jsx
  src/pages/stock/detail/newstab/Newstab.jsx
  src/pages/stock/detail/newstab/Newstab.style.js
Labels: ✨ Feature, :page_facing_up: task

#57 ✨feat: 연관키워드 그래프 및 기사리스트 구현 완료
  package-lock.json
  public/assets/images/related_mark.png
  public/assets/images/sns_mark.png
  src/components/common/bubble-relatedkeyword/RelatedKeyword.chart.jsx
  src/components/common/bubble-relatedkeyword/RelatedKeyword.jsx
  src/components/common/bubble-relatedkeyword/RelatedKeyword.style.js
  src/components/common/bubble/KeywordBubble.jsx
  src/components/common/bubble/KeywordBubble.style.js
  src/components/common/news/naver-news/Naver.news.jsx
  src/components/common/news/naver-news/Naver.style.js
  src/pages/keyword/Keyword.jsx
  src/pages/keyword/Keyword.style.js
Labels: ✨ Feature, :gem: epic, :page_facing_up: task, 🎨design

#59 FIX: merge 에러 수정
  src/components/common/bubble-relatedkeyword/RelatedKeyword.jsx
Labels: 🐛 fix

#55 ✨Feat: 기업 상세 페이지 공통 컴포넌트 구현
  index.html
  package-lock.json
  package.json
  public/assets/images/chart.png
  src/App.jsx
  src/pages/stock/detail/Stock.detail.jsx
  src/pages/stock/detail/StockDetail.jsx
  src/pages/stock/detail/StockDetail.style.jsx
  src/pages/stock/detail/chart/ChartModal.jsx
  src/pages/stock/detail/chart/StockChart.jsx
  src/pages/stock/detail/maintab/Maintab.jsx
  src/pages/stock/detail/maintab/Maintab.style.js
  src/pages/stock/detail/newstab/Newstab.jsx
  src/pages/stock/detail/newstab/Newstab.style.js
  src/pages/stock/detail/pricetab/Pricetab.jsx
  src/pages/stock/detail/pricetab/Pricetab.style.js
Labels: ✨ Feature

#56 Feat/연관 주식회사 리스트 구현 및 차트 API 연동 후 구현 완료
  package-lock.json
  src/components/common/contents-item/Contents.jsx
  src/components/common/contents-item/Contents.style.js
  src/components/common/search/Search.jsx
  src/components/common/sidebar/Sidebar.jsx
  src/components/common/sidebar/Sidebar.style.js
  src/pages/landing/Landing.Search.jsx
  src/pages/stock/Stock.chart.jsx
  src/pages/stock/Stock.chart.style.js
  src/pages/stock/Stock.jsx
  src/pages/stock/Stock.style.js
  src/pages/stock/StockInfoDetail.jsx
  src/pages/stock/StockInfoDetail.style.js
  src/store/reducers/search.js
Labels: :page_facing_up: task

#66 FIX: 머지 이상 현상 수정
  package.json
  src/App.jsx
  src/components/common/contents-item/Contents.jsx
  src/components/common/contents-item/Contents.style.js
  src/pages/main/Main.jsx
  src/pages/stock/Stock.chart.jsx
  src/pages/stock/Stock.jsx
  src/pages/stock/StockInfoDetail.jsx
  src/pages/stock/StockInfoDetail.style.js
  src/pages/stock/detail/StockDetail.jsx
Labels: 🐛 fix

#68 🐛Fix: 연관주 상세 페이지 연결, 모달 디자인 수정
  src/components/common/contents-item/Contents.jsx
  src/pages/stock/Stock.jsx
  src/pages/stock/StockInfoDetail.jsx
  src/pages/stock/detail/StockDetail.jsx
  src/pages/stock/detail/StockDetail.style.jsx
  src/pages/stock/detail/chart/ChartModal.jsx
Labels: 🐛 fix, 🎨design

#70 ✨feat: 백엔드 API 요청 및 연관키워드 렌더링 구현
  package-lock.json
  package.json
  src/components/common/bubble-relatedkeyword/RelatedKeyword.jsx
  src/lib/apis/News-RelatedKeyword.js
  src/lib/apis/RelatedKeyword.js
Labels: :recycle: refactor, ✨ Feature

#74 ✨feat: 검색어 및 연관키워드 비교 그래프 구현
  package-lock.json
  src/components/common/bubble-relatedkeyword/RelatedKeyword.chart.jsx
  src/components/common/bubble-relatedkeyword/RelatedKeyword.jsx
  src/components/common/bubble-relatedkeyword/RelatedNews.jsx
  src/components/common/news/naver-news/Naver.news.jsx
  src/lib/apis/Google-Graph.js
  src/lib/apis/News-RelatedKeyword.js
  src/lib/apis/RelatedKeyword.js
Labels: :recycle: refactor, ✨ Feature, :page_facing_up: task

#75 ✨Feat: 기업 상세 페이지 차트 자세히 보기 부분 - 기간별 일/주/월/연 별 한투 api로 변경
  public/assets/images/bubbleimg.png
  src/pages/stock/detail/StockDetail.jsx
  src/pages/stock/detail/StockDetail.style.jsx
  src/pages/stock/detail/chart/ChartModal.jsx
  src/pages/stock/detail/chart/StockChart.jsx
  src/pages/stock/detail/chart/StockChart.style.jsx
  src/pages/stock/detail/newstab/Newstab.jsx
  src/pages/stock/detail/newstab/Newstab.style.js
Labels: ✨ Feature, 🎨design, 🖼️add

#79 ✨feat: 로딩 컴포넌트 추가 및 redux 변경시 API 재요청 구현
  package-lock.json
  package.json
  src/components/common/Loading/Loading.jsx
  src/components/common/Loading/Loading.style.js
  src/components/common/bubble-relatedkeyword/RelatedKeyword.jsx
Labels: 🐛 fix, ✨ Feature

#84 Feat/ 해당 키워드의 트래픽과 연관주식을 연동하고 시세를 비교해서 차트 구현 완료
  package-lock.json
  src/App.jsx
  src/components/common/contents-item/Contents.jsx
  src/components/common/contents-item/Contents.style.js
  src/components/common/header/Header.jsx
  src/components/common/search/Search.jsx
  src/components/common/search/Search.style.js
  src/components/common/sidebar/Sidebar.jsx
  src/components/common/sidebar/Sidebar.style.js
  src/pages/landing/Bubble.jsx
  src/pages/landing/Bubble.style.js
  src/pages/landing/Landing.Search.jsx
  src/pages/stock/Stock.chart.jsx
  src/pages/stock/Stock.chart.style.js
  src/pages/stock/Stock.jsx
  src/pages/stock/Stock.style.js
  src/pages/stock/StockInfoDetail.jsx
  src/pages/stock/StockInfoDetail.style.js
  src/store/reducers/darkmode.js
  src/store/store.js
Labels: :page_facing_up: task

#85 🐛Fix: StockDetail페이지 차트 날짜 오류 해결/ 웹소켓 실시간 데이터 로딩 시 로딩 이미지 추가
  public/assets/images/bubbleimg.png
  public/assets/images/wsloading.png
  src/pages/stock/detail/StockDetail.jsx
  src/pages/stock/detail/chart/StockChart.jsx
  src/pages/stock/detail/newstab/Newstab.jsx
Labels: 🐛 fix

#90 Feat: 소셜 분석 페이지 요약해서 보여주기
  public/assets/images/decrease.svg
  public/assets/images/increase.svg
  public/assets/images/search.svg
  src/components/common/graphs/normalGraph/NormalGraph.jsx
  src/components/common/header/Header.jsx
  src/components/common/news/keyword-blog/Keyword.blog.jsx
  src/pages/main/Main.jsx
  src/pages/main/Main.style.js
  src/pages/main/RelatedStock.style.js
  src/pages/main/RelatedStockContent.jsx
  src/pages/main/SearchContent.jsx
  src/pages/main/contents-item/ContentHeader.jsx
  src/pages/main/contents-item/ContentHeader.style.js
  src/pages/main/contents-item/Contents.style.js
  src/pages/main/contents-item/StockContent.jsx
  src/pages/stock/Stock.style.js
Labels: ✨ Feature, :page_facing_up: task

#93 ✨Feat: 소셜 페이지 google 분석 보기 구현 완료
  src/components/common/chart-select-bar/country/Country.style.js
  src/components/common/chart-select-bar/period/Period.select.bar.jsx
  src/components/common/chart-select-bar/period/Period.style.js
  src/components/common/keywordGraph/googleGraph/GoogleGraph.jsx
  src/components/common/news/google-news/Google.news.jsx
  src/components/common/news/google-news/Google.style.js
  src/pages/social/Google.item.jsx
  src/pages/social/Google.style.js
Labels: :page_facing_up: task

#94 ✨Feat: 통합페이지 연관어 버블 컴포넌트 구현
  public/assets/images/bell.svg
  src/components/common/bubble-relatedkeyword/RelatedKeyword.style.js
  src/pages/main/Main.jsx
  src/pages/main/RelatedKeyword.jsx
  src/pages/main/RelatedKeyword.style.jsx
  src/pages/main/contents-item/ContentHeader.style.js
  src/pages/stock/detail/StockDetail.style.jsx
Labels: ✨ Feature, 🎨design, 🖼️add

#95 STYLE: 에러 이미지 컴포넌트 구현
  public/assets/images/no-google-trends.svg
  public/assets/images/no-search.svg
  src/pages/main/RelatedStockContent.jsx
  src/pages/main/SearchContent.jsx
Labels: 💄 style, ✨ Feature

#100 Feat/ 소셜 페이지 youtube 분석 보기 구현 완료
  package-lock.json
  package.json
  src/components/common/keywordGraph/googleGraph/GoogleGraph.jsx
  src/components/common/keywordGraph/youtubeGraph/YoutubeGraph.jsx
  src/components/common/news/google-news/Google.style.js
  src/components/common/news/youtube-data/Youtube.data.jsx
  src/components/common/news/youtube-data/Youtube.data.style.js
  src/pages/social/Google.item.jsx
  src/pages/social/Youtube.item.jsx
  src/pages/social/Youtube.style.js
  src/pages/stock/Stock.jsx
Labels: :page_facing_up: task

#101 design: landing page UI 수정
  public/assets/images/landing.png
  public/assets/images/landing2.png
  public/assets/images/logo2.png
  public/assets/images/logo3.png
  public/assets/images/logo4 (2).png
  public/assets/images/logo4.png
  src/pages/landing/Bubble.jsx
  src/pages/landing/Bubble.style.js
  src/pages/landing/Landing.Search.jsx
  src/pages/landing/Landing.Search.style.js
  src/pages/landing/Landing.style.js
Labels: 💄 style, 🎨design, 🖼️add

#105 feat: 연관키워드 그래프 Toop tip 구현 및 관련뉴스 건수 추가
  public/assets/images/question_mark.png
  src/components/common/bubble-relatedkeyword/RelatedKeyword.chart.jsx
  src/components/common/bubble-relatedkeyword/RelatedKeyword.jsx
  src/components/common/bubble-relatedkeyword/RelatedKeyword.style.js
  src/components/common/bubble-relatedkeyword/RelatedNews.jsx
  src/components/common/bubble/KeywordBubble.jsx
  src/components/common/bubble/KeywordBubble.style.js
  src/components/common/news/naver-news/Naver.style.js
  src/components/common/search/Search.jsx
  src/components/common/sidebar/Sidebar.jsx
  src/pages/keyword/Keyword.style.js
  src/pages/landing/Landing.Search.jsx
  src/pages/main/SearchContent.jsx
  src/pages/social/Google.item.jsx
  src/pages/stock/StockInfoDetail.jsx
Labels: ✨ Feature, 🖼️add

#107 Feat/ naver 분석 보기 구현 , 소셜 페이지 에러 화면 적용 및 다크 모드 적용 완료
  public/assets/images/YouTube_logo.png
  src/components/common/bubble-relatedkeyword/RelatedKeyword.chart.jsx
  src/components/common/chart-select-bar/period/Period.select.bar.jsx
  src/components/common/chart-select-bar/period/Period.style.js
  src/components/common/keywordGraph/naverGraph/NaverGraph.jsx
  src/components/common/keywordGraph/youtubeGraph/YoutubeGraph.jsx
  src/components/common/news/google-news/Google.news.jsx
  src/components/common/news/google-news/Google.style.js
  src/components/common/news/naver-news/Naver.news.jsx
  src/components/common/news/naver-news/Naver.style.js
  src/components/common/news/youtube-data/Youtube.data.jsx
  src/lib/apis/Google-Graph.js
  src/pages/social/Google.item.jsx
  src/pages/social/Google.style.js
  src/pages/social/NaverItem.jsx
  src/pages/social/NaverItem.style.js
  src/pages/social/Social.jsx
  src/pages/social/Social.style.js
  src/pages/social/Youtube.item.jsx
  src/pages/social/Youtube.style.js
  src/pages/stock/Stock.jsx
Labels: :page_facing_up: task

#111 FEAT: 에러 페이지 추가 및 각종 에러 수정
  index.html
  public/assets/images/error-icon.png
  public/assets/images/not-found-icon.png
  src/App.jsx
  src/components/common/bubble-relatedkeyword/RelatedKeyword.chart.jsx
  src/components/common/error/ErrorBoundary.jsx
  src/components/common/error/ErrorPage.jsx
  src/components/common/error/NotFoundPage.jsx
  src/pages/landing/Landing.Search.jsx
  src/pages/main/Main.jsx
  src/pages/main/RelatedStockContent.jsx
  src/pages/main/SearchContent.jsx
Labels: 🐛 fix, :recycle: refactor, ✨ Feature, 🎨design

#112 ✨feat: 연관키워드 페이지 다크모드 적용
  package-lock.json
  src/components/common/bubble-relatedkeyword/RelatedKeyword.chart.jsx
  src/components/common/bubble-relatedkeyword/RelatedKeyword.jsx
  src/components/common/bubble-relatedkeyword/RelatedKeyword.style.js
  src/components/common/bubble-relatedkeyword/RelatedNews.jsx
  src/components/common/bubble/KeywordBubble.jsx
  src/components/common/bubble/KeywordBubble.style.js
  src/components/common/news/naver-news/Naver.style.js
  src/lib/apis/Google-Graph.js
  src/pages/keyword/Keyword.jsx
  src/pages/keyword/Keyword.style.js
Labels: ✨ Feature, 🎨design

#113 🐛fix: 메인 페이지 에러 컴포넌트 추가
  package-lock.json
  src/pages/main/Main.jsx
  src/pages/main/Main.style.js
  src/pages/main/RelatedSns.jsx
  src/pages/main/RelatedStockContent.jsx
  src/pages/main/SearchContent.jsx
  src/pages/main/contents-item/ContentHeader.jsx
  src/pages/main/contents-item/ContentHeader.style.js
  src/pages/main/contents-item/Contents.style.js
  src/pages/main/contents-item/Instagram.jsx
  src/pages/main/contents-item/StockContent.jsx
  src/pages/main/contents-item/YoutubeVideo.jsx
Labels: 🐛 fix, ✨ Feature

#114 Fix/design darkmode
  src/pages/main/RelatedKeyword.style.jsx
  src/pages/main/contents-item/YoutubeVideo.jsx
  src/pages/main/contents-item/YoutubeVideo.style.js
  src/pages/stock/detail/StockDetail.jsx
  src/pages/stock/detail/StockDetail.style.jsx
  src/pages/stock/detail/chart/ChartModal.jsx
  src/pages/stock/detail/chart/ChartModal.style.js
  src/pages/stock/detail/chart/StockChart.jsx
  src/pages/stock/detail/chart/StockChart.style.jsx
  src/pages/stock/detail/maintab/Maintab.jsx
  src/pages/stock/detail/maintab/Maintab.style.js
  src/pages/stock/detail/newstab/Newstab.jsx
  src/pages/stock/detail/newstab/Newstab.style.js
  src/pages/stock/detail/pricetab/Pricetab.jsx
  src/pages/stock/detail/pricetab/Pricetab.style.js
Labels: ✨ Feature

#118 Feat/ Instagram 분석 보기 및 소셜 페이지 에러 화면 적용 완료
  package-lock.json
  src/components/common/keywordGraph/instagramGraph/InstagramIndexes.jsx
  src/components/common/news/google-news/Google.news.jsx
  src/components/common/news/instagram-data/instagram.data.jsx
  src/components/common/news/instagram-data/instagram.data.style.js
  src/components/common/news/naver-news/Naver.style.js
  src/components/common/news/youtube-data/Youtube.data.jsx
  src/pages/social/Google.item.jsx
  src/pages/social/Google.style.js
  src/pages/social/Instagram.item.jsx
  src/pages/social/Instagram.style.js
  src/pages/social/NaverItem.jsx
  src/pages/social/Youtube.item.jsx
Labels: :page_facing_up: task

#120 DESIGN: blurdiv 규격 및 다크모드 설정
  src/components/common/bubble-relatedkeyword/RelatedNews.jsx
  src/components/common/news/google-news/Google.style.js
  src/components/common/news/instagram-data/instagram.data.style.js
  src/components/common/news/naver-news/Naver.style.js
  src/components/common/news/youtube-data/Youtube.data.style.js
  src/pages/main/contents-item/YoutubeVideo.jsx
Labels: :recycle: refactor, ✨ Feature

#121 ✨feat: files - 통합 페이지 다크 모드 적용
  src/pages/main/RelatedKeyword.jsx
  src/pages/main/RelatedKeyword.style.jsx
  src/pages/main/RelatedSns.jsx
  src/pages/main/RelatedSns.style.js
  src/pages/main/RelatedStockContent.jsx
  src/pages/main/SearchContent.jsx
  src/pages/main/contents-item/ContentHeader.jsx
  src/pages/main/contents-item/Contents.style.js
  src/pages/main/contents-item/Instagram.jsx
  src/pages/main/contents-item/YoutubeVideo.jsx
Labels: ✨ Feature

#125 ✨feat: 연관키워드 페이지 google에서 naver API로 이관
  src/App.jsx
  src/components/common/bubble-relatedkeyword/Chart_Background.css
  src/components/common/bubble-relatedkeyword/RelatedKeyword.chart.jsx
  src/components/common/bubble-relatedkeyword/RelatedKeyword.style.js
  src/components/common/bubble-relatedkeyword/RelatedNews.jsx
  src/components/common/news/naver-news/Naver.style.js
  src/lib/apis/Google-Graph.js
  src/lib/apis/Naver-Trends.js
  src/pages/keyword/Keyword.jsx
  src/pages/keyword/Keyword.style.js
  src/pages/main/RelatedKeyword.jsx
  src/pages/social/NaverItem.jsx
Labels: 🐛 fix, ✨ Feature, 🎨design

#126 Feat/related error
  src/components/common/contents-item/Contents.jsx
  src/components/common/contents-item/Contents.style.js
  src/components/common/header/Header.style.js
  src/components/common/keywordGraph/youtubeGraph/YoutubeGraph.jsx
  src/components/common/news/google-news/Google.news.jsx
  src/components/common/news/google-news/Google.style.js
  src/components/common/news/youtube-data/Youtube.data.jsx
  src/components/common/news/youtube-data/Youtube.data.style.js
  src/components/common/search/Search.jsx
  src/components/common/search/Search.style.js
  src/components/common/sidebar/Sidebar.jsx
  src/pages/keyword/Keyword.jsx
  src/pages/main/contents-item/YoutubeVideo.jsx
  src/pages/social/Google.item.jsx
  src/pages/social/Google.style.js
  src/pages/social/NaverItem.jsx
  src/pages/social/Social.jsx
  src/pages/social/Social.style.js
  src/pages/social/Youtube.item.jsx
  src/pages/social/Youtube.style.js
  src/pages/stock/Stock.chart.jsx
  src/pages/stock/Stock.chart.style.js
  src/pages/stock/Stock.jsx
  src/pages/stock/Stock.style.js
  src/store/reducers/darkmode.js
Labels: :page_facing_up: task

#128 🐛fix: YoutubeGraph.jsx - 유튜브 그래프 에러 수정
  src/components/common/keywordGraph/youtubeGraph/YoutubeGraph.jsx
Labels: 🐛 fix

#129 ✨ feat: 통합 페이지 차트 네이버 데이터랩으로 변경
  src/components/common/keywordGraph/youtubeGraph/YoutubeGraph.jsx
  src/pages/main/SearchContent.jsx
  src/pages/social/NaverItem.jsx
Labels: :page_facing_up: task

#130 ✨ feat: 소셜 페이지 에러 해결
  src/components/common/keywordGraph/youtubeGraph/YoutubeGraph.jsx
  src/pages/main/SearchContent.jsx
Labels: :page_facing_up: task

#132 ✨feat: 에러 이미지 추가
  public/assets/images/white-logo.png
  src/components/common/logo/Logo.jsx
  src/components/common/logo/Logo.style.js
  src/pages/main/RelatedKeyword.jsx
  src/pages/main/RelatedKeyword.style.jsx
  src/pages/main/contents-item/Instagram.jsx
Labels: ✨ Feature, 🎨design

#133 ✨ feat: 연관 주식 페이지 차트 에러 해결
  src/components/common/news/youtube-data/Youtube.data.jsx
  src/pages/stock/Stock.chart.jsx
Labels: :page_facing_up: task

#136 🐛fix: RelatedKeyword.jsx - 로딩에 다크모드 적용 안되는 현상 수정
  src/pages/main/RelatedKeyword.jsx
Labels: 🐛 fix

#138 🐛fix: RelatedKeyword.jsx - 진짜 머지 에러 수정
  src/pages/main/RelatedKeyword.jsx
Labels: 🐛 fix

#139 ✨feat: index.html - noto-Sans-KR 폰트 적용
  README.md
  index.html
  src/pages/stock/detail/StockDetail.jsx
Labels: 🎨design
